chore: Configure license headers (#115)
* chore: configure licensure

* chore: Apply licensure

Ran `licensure -p --in-place`.

* ci: run licensure in CI

* ci: prefer binstall

* ci: Add hints for fixing

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -84,16 +84,18 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
       - name: Install cargo-machete
-        uses: clechasseur/rs-cargo@v2
+        uses: taiki-e/install-action@v2
         with:
-          command: install
-          args: cargo-machete@0.8.0
+          tool: cargo-machete
       - name: Run cargo-machete
-        uses: clechasseur/rs-cargo@v2
-        with:
-          command: machete
-          args: --with-metadata
-          working-directory: stepflow-rs
+        working-directory: stepflow-rs
+        run: |
+          cargo machete --with-metadata
+          exit_code=$?
+          if [ $exit_code -ne 0 ]; then
+            echo "::error::Unused deps check failed. Run \`cargo machete --fix --with-metadata\` to fix."
+            exit $exit_code
+          fi
 
   rust-cargo-deny:
     name: Rust Cargo Deny
@@ -103,3 +105,22 @@ jobs:
       - uses: EmbarkStudios/cargo-deny-action@v2
         with:
           manifest-path: stepflow-rs/Cargo.toml
+
+  licensure:
+    name: Licensure
+    runs-on: ubuntu-22.04
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Install licensure
+        uses: taiki-e/install-action@v2
+        with:
+          tool: licensure
+      - name: Run licensure
+        run: |
+          licensure -c -p
+          exit_code=$?
+          if [ $exit_code -ne 0 ]; then
+            echo "::error::License check failed. Run \`licensure -p --in-place\` to fix."
+            exit $exit_code
+          fi
